### ISSUE TITLE
IndexError: index 109 is out of bounds for axis 0 with size 11

### ISSUE THREAD

**Issue by luisfredgs** [rpaudel42/Pikachu#5]
```python
Estimating Edge Probability Distribution....
++++++++++ Parameters +++++++
Learning Rate:  0.001
# of Support Set:  10
Param File:  weights/param_optc_sample_d64_0.001_10.pickle

I've encountered the following error while using the sample:
Generating Training Edges....
  0%|                                                                                                                                 | 0/5 [00:00<?, ?it/s]G:  356 112884
  0%|                                                                                                                                 | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/luisfredgs/Documents/ML_Projects/Pikachu/main.py", line 114, in <module>
    ad_long_term.anomaly_detection(graphs, param_file='weights/param' + param_file_name)
  File "/home/luisfredgs/Documents/ML_Projects/Pikachu/anomaly_detection.py", line 180, in anomaly_detection
    train_x, train_y = self.get_train_edges(graphs[:self.args.trainwin], self.args.support)
  File "/home/luisfredgs/Documents/ML_Projects/Pikachu/anomaly_detection.py", line 114, in get_train_edges
    H = self.aggregate_neighbors_object(u, support_set)
  File "/home/luisfredgs/Documents/ML_Projects/Pikachu/anomaly_detection.py", line 64, in aggregate_neighbors_object
    CNu = [self.node_embeddings[self.idx][self.node_list.index(str(n))] for n in n_u]
  File "/home/luisfredgs/Documents/ML_Projects/Pikachu/anomaly_detection.py", line 64, in <listcomp>
    CNu = [self.node_embeddings[self.idx][self.node_list.index(str(n))] for n in n_u]
IndexError: index 109 is out of bounds for axis 0 with size 11
```

**Comment by luisfredgs** [comment]
I resolved the issue by commenting out the following line: https://github.com/rpaudel42/Pikachu/blob/af5fce843cad2cd5e9bb44601b0509d3f0d20218/main.py#L107.
